// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20201218132021_AddTimestampToQrtrlyTable")]
    partial class AddTimestampToQrtrlyTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("API.Entities.Stock", b =>
                {
                    b.Property<int>("stockID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("companyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("industry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.Property<string>("stockSymbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("stockID");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("API.Entities.StockFundamentalAttributes", b =>
                {
                    b.Property<int>("StockFundamentalAttributeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Head")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RecordTimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Statement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Y0")
                        .HasColumnType("decimal(20,5)");

                    b.Property<decimal>("Y1")
                        .HasColumnType("decimal(20,5)");

                    b.Property<decimal>("Y2")
                        .HasColumnType("decimal(20,5)");

                    b.Property<decimal>("Y3")
                        .HasColumnType("decimal(20,5)");

                    b.Property<decimal>("Y4")
                        .HasColumnType("decimal(20,5)");

                    b.Property<decimal>("Y5")
                        .HasColumnType("decimal(20,5)");

                    b.Property<decimal>("Y6")
                        .HasColumnType("decimal(20,5)");

                    b.Property<decimal>("Y7")
                        .HasColumnType("decimal(20,5)");

                    b.Property<decimal>("Y8")
                        .HasColumnType("decimal(20,5)");

                    b.Property<decimal>("Y9")
                        .HasColumnType("decimal(20,5)");

                    b.Property<decimal?>("observationValue")
                        .HasColumnType("decimal(20,5)");

                    b.Property<string>("observationValueType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("stockID")
                        .HasColumnType("int");

                    b.HasKey("StockFundamentalAttributeID");

                    b.HasIndex("stockID");

                    b.ToTable("StockFundamentalAttributes");
                });

            modelBuilder.Entity("API.Entities.StockQuarterlyData", b =>
                {
                    b.Property<int>("StockQuarterlyDataID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Narration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Q0")
                        .HasColumnType("decimal(20,5)");

                    b.Property<decimal>("Q1")
                        .HasColumnType("decimal(20,5)");

                    b.Property<decimal>("Q2")
                        .HasColumnType("decimal(20,5)");

                    b.Property<decimal>("Q3")
                        .HasColumnType("decimal(20,5)");

                    b.Property<decimal>("Q4")
                        .HasColumnType("decimal(20,5)");

                    b.Property<decimal>("Q5")
                        .HasColumnType("decimal(20,5)");

                    b.Property<decimal>("Q6")
                        .HasColumnType("decimal(20,5)");

                    b.Property<decimal>("Q7")
                        .HasColumnType("decimal(20,5)");

                    b.Property<decimal>("Q8")
                        .HasColumnType("decimal(20,5)");

                    b.Property<decimal>("Q9")
                        .HasColumnType("decimal(20,5)");

                    b.Property<DateTime>("RecordTimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("observationValue")
                        .HasColumnType("decimal(20,5)");

                    b.Property<string>("observationValueType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("stockID")
                        .HasColumnType("int");

                    b.HasKey("StockQuarterlyDataID");

                    b.HasIndex("stockID");

                    b.ToTable("StockQuarterlyData");
                });

            modelBuilder.Entity("API.Entities.StockFundamentalAttributes", b =>
                {
                    b.HasOne("API.Entities.Stock", "stock")
                        .WithMany()
                        .HasForeignKey("stockID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("stock");
                });

            modelBuilder.Entity("API.Entities.StockQuarterlyData", b =>
                {
                    b.HasOne("API.Entities.Stock", "stock")
                        .WithMany()
                        .HasForeignKey("stockID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("stock");
                });
#pragma warning restore 612, 618
        }
    }
}
